version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --bind_ip_all --auth
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - back_net
  import:
    build: .
    depends_on:
      - db
    environment:
      MONGO_HOST: db
      MONGO_PORT: "27017"
      MONGO_USER: admin
      MONGO_PASSWORD: admin123
      MONGO_DB: test
      MONGO_COLLECTION: restaurants
      JSON_FILE: /data/restaurants.json
    volumes:
      - ./data:/data
    networks:
      - back_net
  backend:
    build: ./API
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - back_net
      - front_net
  frontend:
    build: ./Frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - front_net
networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge
